# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAlbum', models.TextField()),
                ('tag', models.TextField(blank=True)),
                ('releasedate', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Music_App')),
                ('web', models.URLField(blank=True)),
                ('Library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='musicapp.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomArtista', models.TextField()),
                ('tags', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Music_App')),
                ('web', models.URLField(blank=True)),
                ('similars', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('Library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='musicapp.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTrack', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Music_App')),
                ('web', models.URLField(blank=True)),
                ('duration', models.IntegerField(blank=True)),
                ('playcount', models.IntegerField(blank=True)),
                ('published', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('Library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='musicapp.Library')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.Album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.Artist'),
        ),
    ]
