# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_auto_20160520_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='date',
        ),
        migrations.RemoveField(
            model_name='track',
            name='date',
        ),
    ]
