# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20160520_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='country',
            new_name='genere',
        ),
    ]
