# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAlbum', models.TextField()),
                ('tag', models.TextField()),
                ('releasedate', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='MusicApp')),
                ('web', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomArtista', models.TextField()),
                ('tags', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='MusicApp')),
                ('web', models.URLField()),
                ('similars', models.TextField()),
                ('summary', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTrack', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='MusicApp')),
                ('web', models.URLField()),
                ('duration', models.IntegerField()),
                ('playcount', models.IntegerField()),
                ('published', models.TextField()),
                ('summary', models.TextField()),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='MusicApp2.Album')),
                ('artista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='MusicApp2.Artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='MusicApp2.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
